version: '3.8'

services:
  # PHP-FPM service for processing PHP
  php-fpm:
    build: .
    environment:
      - MTT_DB_TYPE=postgres
      - MTT_DB_HOST=postgres
      - MTT_DB_NAME=mytinytodo
      - MTT_DB_USER=mtt
      - MTT_DB_PASSWORD=password123
      - MTT_DB_PREFIX=mtt_
    # Uncomment the following line to use environment file
    # env_file: .env
    volumes:
      - app_files:/var/www/html
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  # Nginx service for web serving
  nginx:
    image: nginx:1.24-alpine
    ports:
      - "8080:8080"
    volumes:
      - app_files:/var/www/html:ro  # Read-only access to app files
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=mytinytodo
      - POSTGRES_USER=mtt
      - POSTGRES_PASSWORD=password123
    # Uncomment the following line to use environment file
    # env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose PostgreSQL port for external access if needed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mtt -d mytinytodo"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
  app_files:  # Shared volume for application files

networks:
  app-network:
    driver: bridge