# Default values for mytinytodo
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: mytinytodo
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 33  # www-data group

securityContext:
  runAsNonRoot: true
  runAsUser: 33  # www-data user
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: mytinytodo.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: mytinytodo-tls
  #    hosts:
  #      - mytinytodo.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Application configuration
config:
  # Database configuration
  database:
    type: postgres
    host: ""  # Will use PostgreSQL service name if empty
    port: 5432
    name: mytinytodo
    user: mytinytodo
    password: ""  # Will be generated if empty
    prefix: mtt_
  
  # Application settings
  app:
    salt: ""  # Will be generated if empty
    debug: false
    disableExtensions: false
    apiUsePathInfo: false

# PostgreSQL configuration (using Bitnami PostgreSQL chart)
postgresql:
  enabled: false
  auth:
    postgresPassword: ""  # Will be generated if empty
    username: mytinytodo
    password: ""  # Will be generated if empty
    database: mytinytodo
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
  metrics:
    enabled: false

# External PostgreSQL configuration (when postgresql.enabled = false)
externalDatabase:
  host: ""
  port: 5432
  username: mytinytodo
  password: ""
  database: mytinytodo
  existingSecret: ""
  existingSecretPasswordKey: "postgresql-password"

# Persistent Volume for application data (logs, uploads, etc.)
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""

# Health checks
healthcheck:
  enabled: true
  path: /
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3