name: Docker Image CI

on:
  release:
    types: [created]
  # Optional: Keep manual trigger for testing
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from release
      id: extract_version
      run: |
        if [ "${{ github.event.release.tag_name }}" != "" ]; then
          # Remove 'v' prefix if present (e.g., v1.0.0 -> 1.0.0)
          VERSION="${{ github.event.release.tag_name }}"
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        else
          echo "version=latest" >> $GITHUB_OUTPUT
          echo "tag=latest" >> $GITHUB_OUTPUT
        fi
    
    - name: Build Docker Image and Push to GHCR, Docker Hub, or AWS ECR
      uses: GlueOps/github-actions-build-push-containers@v0.4.1
      with:
        # Use version from GitHub release tag
        tags: ${{ steps.extract_version.outputs.version }},latest 
              
