name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * 1' # every monday
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2
        with:
          owner: sleungcy # owner of the fork
          repo: mytinytodo # repo name of the fork
          base: main # branch on the fork
          head: master # branch on the upstream
          merge_method: merge
