name: helm package

on:
  release:
    types: [created]
  # Optional: Keep manual trigger for testing
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install helm
        uses: Azure/setup-helm@v4
        with:
          version: '3.13.0'  # Use a specific modern Helm version

      - name: login to ghcr using helm
        shell: bash    
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.repository_owner }} --password-stdin

      - name: Install PyBump
        run: |
          python3 -m pip install pybump
        shell: bash
        
      - name: Extract version from release
        id: extract_version
        run: |
          if [ "${{ github.event.release.tag_name }}" != "" ]; then
            # Remove 'v' prefix if present (e.g., v1.0.0 -> 1.0.0)
            VERSION="${{ github.event.release.tag_name }}"
            VERSION=${VERSION#v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            # Fallback to chart version if no release tag
            version=$(pybump get --file ./helm/mytinytodo/Chart.yaml)
            echo "version=$version" >> $GITHUB_OUTPUT
          fi

      - name: Helm Chart
        run : |
          set -x
          version=${{ steps.extract_version.outputs.version }}
          helm package \
          ./helm/mytinytodo \
          --app-version $version \
          --version $version        
          ls mytinytodo-chart-*.tgz | xargs -I {} helm push {} oci://ghcr.io/${{ github.repository_owner }}
        shell: bash